version: "3.2"

services:
  meeting-server:
    image: hardcoreeng/meeting-service
    ports:
      - 18081:18081
    links:
      - kms
    environment:
      - WEB_HOST=${WEB_HOST} # Should be
      - SERVER_PORT=18081
      - SERVER_SECRET=${SERVER_SECRET}
      - SECURITY_CERT_FILE=/app/cert/cert.crt
      - SECURITY_KEY_FILE=/app/cert/cert.key
      - SECURITY_CA_FILE=
      - KMS_URL=ws://kms:8888/kurento
    volumes:
      - ./cert:/app/cert
  kms:
    image: kurento/kurento-media-server:6
    volumes:
      - type: bind
        source: ./kurento
        target: /etc/kurento
    ports:
      - 5000-5500:5000-5500
    expose:
      - 8888
    restart: unless-stopped

